### PR TITLE
feat: Add rudimentary TypeScript types.

### PR DESCRIPTION
**Pull request by goloroden**
This PR adds at least some basic typings for TypeScript, and refers to #130

### CODE REVIEW

**Comment by Zaseth** [comment]
Thanks for this.

**Comment by goloroden** [comment]
More than two weeks passed without *any* feedback, hence I am going to close this.

**Comment by ChALkeR** [comment]
@goloroden Sorry for the delay on this.
Merged and updated with more options.

**Comment by ChALkeR** [comment]
Published as `v1.0.0-rc.3`. Likely that's the last release before `v1.0.0`.

**Pull request closed without merging**
